# Generated by Django 4.2.4 on 2023-09-13 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myresume',
            name='git',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
