# Generated by Django 4.2.4 on 2023-09-15 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0002_myresume_git'),
    ]

    operations = [
        migrations.CreateModel(
            name='resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='media')),
                ('ability', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('mobile', models.CharField(max_length=14)),
                ('email', models.EmailField(max_length=250)),
                ('github_id', models.CharField(max_length=250)),
                ('linkedin_id', models.CharField(max_length=250)),
                ('address', models.CharField(max_length=50)),
                ('years_degree', models.CharField(max_length=15)),
                ('name_degree', models.CharField(max_length=30)),
                ('clg_name', models.CharField(max_length=100)),
                ('year12th', models.CharField(max_length=15)),
                ('class_name12th', models.CharField(max_length=10)),
                ('school_name12th', models.CharField(max_length=100)),
                ('year10th', models.CharField(max_length=15)),
                ('class_name10th', models.CharField(max_length=10)),
                ('school_name10th', models.CharField(max_length=100)),
                ('language_1', models.CharField(max_length=50)),
                ('percentage_1', models.IntegerField()),
                ('language_2', models.CharField(max_length=50)),
                ('percentage_2', models.IntegerField()),
                ('para_1', models.CharField(max_length=500)),
                ('para_2', models.CharField(max_length=500)),
                ('working_years_1', models.CharField(max_length=50)),
                ('company_name_1', models.CharField(max_length=50)),
                ('designation_1', models.CharField(max_length=50)),
                ('about_1', models.CharField(max_length=250)),
                ('working_years_2', models.CharField(max_length=50)),
                ('company_name_2', models.CharField(max_length=50)),
                ('designation_2', models.CharField(max_length=50)),
                ('about_2', models.CharField(max_length=250)),
                ('skill_1', models.CharField(max_length=50)),
                ('percent_1', models.IntegerField()),
                ('skill_2', models.CharField(max_length=50)),
                ('percent_2', models.IntegerField()),
                ('skill_3', models.CharField(max_length=50)),
                ('percent_3', models.IntegerField()),
                ('skill_4', models.CharField(max_length=50)),
                ('percent_4', models.IntegerField()),
                ('skill_5', models.CharField(max_length=50)),
                ('percent_5', models.IntegerField()),
                ('skill_6', models.CharField(max_length=50)),
                ('percent_6', models.IntegerField()),
                ('interest_1', models.CharField(max_length=50)),
                ('interest_2', models.CharField(max_length=50)),
                ('interest_3', models.CharField(max_length=50)),
                ('interest_4', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='myresume',
        ),
    ]
