# Generated by Django 4.2.4 on 2023-09-16 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0003_resume_delete_myresume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='interest_2',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='interest_3',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='interest_4',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='language_2',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='para_2',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='percent_2',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='percent_3',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='percent_4',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='percent_5',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='percent_6',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='percentage_2',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='skill_2',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='skill_3',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='skill_4',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='skill_5',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='skill_6',
        ),
    ]
