# Generated by Django 4.2.4 on 2023-09-06 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_details',
            name='mobile_no',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
